# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Belper Community Church
email: office@belpercommunitychurch.org
phone: 01773 441 211
description: > # this means to ignore newlines until "baseurl:"
  Missional church serving Belper and wider afield.
baseurl: "" # the subpath of your site, e.g. /blog
themeurl: "/themes/Intensely"
url: "http://belpercommunitychurch.org" # the base hostname & protocol for your site
twitter_username: belpercc
github_username:  berthelemy

# Build settings
markdown: kramdown

include: ["_pages"]
permalink: /:title/

collections:
  sliders:
  events:
    output: true
    permalink: /calendar/:path/